### ISSUE TITLE
[Help] User feed

### ISSUE THREAD

**Issue by levifranzen** [shitgram/node-shitgram#1]
Are there any plans in the roadmap to scrap the user feed? Or is it just me who is not using shitgram properly?

**Comment by ruj** [comment]
There is still no way to get the user feed directly, an alternative action is to enable the default response in the method if available where you want to get native instagram information.

**Comment by levifranzen** [comment]
Tried using **true** and got this error:
TypeError: Cannot create property 'defaultResponse' on boolean 'true'
    at Shitgram.user (/rbd/pnpm-volume/2667fb4f-7469-4f04-8c5b-0a99d32fa446/node_modules/shitgram/lib/Shitgram.js:128:27)

It is running at https://glitch.com/~ubiquitous-key
