### ISSUE TITLE
defaultResponse: true

### ISSUE THREAD

**Issue by levifranzen** [shitgram/node-shitgram#2]
Tried using defaultResponse **true** and got this error:
TypeError: Cannot create property 'defaultResponse' on boolean 'true'
at Shitgram.user (/rbd/pnpm-volume/2667fb4f-7469-4f04-8c5b-0a99d32fa446/node_modules/shitgram/lib/Shitgram.js:128:27)

It is running at https://glitch.com/~ubiquitous-key

**Comment by ruj** [comment]
The options for each method are objects.
Change the second parameter `true` to an object containing `defaultResponse: true` so that this error does not occur.

**Comment by levifranzen** [comment]
Thank you, I'll learn Node properly first.
